[0m12:30:38.270222 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1051df750>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105786610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105786c50>]}


============================== 12:30:38.272583 | 106a8ea0-8bb6-45ae-8935-a2eb9fedeaf6 ==============================
[0m12:30:38.272583 [info ] [MainThread]: Running with dbt=1.6.1
[0m12:30:38.272910 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/bsmith/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt init', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:30:42.649927 [debug] [MainThread]: Starter project path: /Users/bsmith/dbt_core/dbt-env/lib/python3.11/site-packages/dbt/include/starter_project
[0m12:30:42.660843 [info ] [MainThread]: 
Your new dbt project "idexx_test" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:30:42.661526 [info ] [MainThread]: Setting up your profile.
[0m12:30:42.663813 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m12:30:42.664790 [debug] [MainThread]: Command `dbt init` failed at 12:30:42.664588 after 4.40 seconds
[0m12:30:42.665356 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1054b8b50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1054ba4d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10521c390>]}
[0m12:30:42.665908 [debug] [MainThread]: Flushing usage events
[0m12:42:08.134189 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106d6c6d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106e18250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107084850>]}


============================== 12:42:08.137088 | 163ed21b-f407-49f4-9f4f-fa73885aff81 ==============================
[0m12:42:08.137088 [info ] [MainThread]: Running with dbt=1.6.1
[0m12:42:08.137417 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/Users/bsmith/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt seed', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m12:42:08.137720 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/bsmith/idexx/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:42:08.138062 [debug] [MainThread]: Command `dbt seed` failed at 12:42:08.137999 after 0.01 seconds
[0m12:42:08.138257 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106e13f10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104b4a750>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106e18850>]}
[0m12:42:08.138436 [debug] [MainThread]: Flushing usage events
